apiVersion: apps/v1
kind: Deployment
metadata:
  name: backstage
  namespace: backstage
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backstage
  template:
    metadata:
      labels:
        app: backstage
    spec:
      containers:
        - name: backstage
          image: yarche/ct-backend:helm-1.0.0
#          image: yarche/ct-backend:tmp-1.0.0
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 7007
          envFrom:
            - secretRef:
                name: postgres-secrets
            - secretRef:
                name: backstage-secrets
          env:
            - name: POSTGRES_HOST
              value: postgres
            - name: POSTGRES_USER
              value: postgres
            - name: AUTH_GOOGLE_CLIENT_ID
              value: AUTH_GOOGLE_CLIENT_ID
            - name: AUTH_GOOGLE_CLIENT_SECRET
              value: AUTH_GOOGLE_CLIENT_SECRET
            - name: BACKEND_SECRET
              value: BACKEND_SECRET
# Uncomment if health checks are enabled in your app:
# https://backstage.io/docs/plugins/observability#health-checks
#          readinessProbe:
#            httpGet:
#              port: 7007
#              path: /healthcheck
#          livenessProbe:
#            httpGet:
#              port: 7007
#              path: /healthcheck

