apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: cake
  description: Team Cake
spec:
  type: team
  parent: engineering
  children: []
---
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: martin.dobberstein
spec:
  memberOf: [cake, vision]