apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: arch
  description: Team Arch
spec:
  type: team
  parent: engineering
  children: []
---
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: grzegorz.krumpholz
spec:
  memberOf: [arch]