apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: data
  description: Team Data
spec:
  type: team
  parent: engineering
  children: []
---
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: sebastian.mika
spec:
  memberOf: [data]