name: build

on:
  push:
    paths:
      - Dockerfile
      - .github/workflows/backstage.yaml
    branches:
      - 'master'
      - 'deploy'
  pull_request:
    paths:
      - Dockerfile
      - .github/workflows/backstage.yaml
    branches:
      - 'master'
      - 'deploy'

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - run: npm -v
      - uses: borales/actions-yarn@v2.3.0
        with:
          cmd: install # will run `yarn install` command


#      - run: |
#  curl -fsSL -o ~/bin/yarn \
#  https://github.com/yarnpkg/yarn/releases/download/v1.22.17/yarn-1.22.17.js
#  chmod +x ~/bin/yarn
