name: build

on:
  push:
    paths:
      - Dockerfile
      - .github/workflows/backstage.yaml
    branches:
      - 'master'
      - 'deploy'
  pull_request:
    paths:
      - Dockerfile
      - .github/workflows/backstage.yaml
    branches:
      - 'master'
      - 'deploy'

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - uses: actions/checkout@v2
      - name: Setup Nodejs
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install Yarn
        run: npm install -g yarn

#      - uses: borales/actions-yarn@v2.3.0
#        with:
#          cmd: install # will run `yarn install` command

      - name: Setup Nodejs with yarn caching
        uses: actions/setup-node@v2
        with:
          node-version: "14"
          cache: yarn

      - name: Versions check
        run: node -v
      - run: npm -v
      - run: yarn -v

      - name: Yarn prepare
        run: yarn install --frozen-lockfile
      - run: NODE_OPTIONS=--max_old_space_size=4096 yarn tsc
      - run: yarn build

      - name: Docker Build
        env:
          TAG: ${{ github.ref_name }}
        run: |
          docker build -t yarche/ct-backend:latest .
          docker tag yarche/ct-backend:latest yarche/ct-backend:${TAG}
      - name: Docker Push
        env:
          TAG: ${{ github.ref_name }}
        run: |
          docker push yarche/ct-backend:latest
          docker push yarche/ct-backend:${TAG}

# Clean-up
      - name: Uninstall Yarn
        run: npm uninstall -g yarn
